---
pool: 
  name: Default

trigger:
  - master

steps:
  - script: sudo apt update && sudo apt install software-properties-common -y && sudo add-apt-repository --yes --update ppa:ansible/ansible && sudo apt install ansible -y
  - script: ansible-playbook -i hosts java.yaml

