pool:
  name: default

trigger:
  - master

steps:
  - task: Maven@3
    displayName: maven install
    inputs:
      mavenPOMFile: 'pom.xml'
      javaHomeOption: 'path'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
      mavenVersionOption: 'path'
      mavenDirectory: '/opt/apache-maven-3.9.0'
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
