---
pool:
  name: default

trigger:
  - master

parameters:
- name: nodejs
  displayName: nodejs install
  type: string
  default: '10.19.0'  
- name: npm
  displayName: npm install
  type: string
  default: 
    - install

- task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodejs }} 
- task: Npm@1
    inputs:
      command: ${{ parameters.npm }} 
