---
pool: 
  vmImage: ubuntu-latest

trigger: 
  - main

steps:
  - task: PipAuthenticate@1
    displayName: python install
    inputs:
      versionSpec: '3.10.6'
  - task: JavaToolInstaller@0
    displayName: java install
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'