---
pool: 
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest
trigger:
  - master

steps:
  - task: Maven@4
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: '1.17'
      mavenDirectory: /spring-petclinic